---
- hosts: webservers

  become: true

  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Copy Custom HTML
      template:
        src: templates/index.html.j2
        dest: /tmp/index.html

    - name: Deploy Nginx
      docker_container:
        name: nginx
        image: nginx:latest

        restart_policy: always

        ports:
          - "80:80"

        volumes:
          - /tmp/index.html:/usr/share/nginx/html/index.html
